title: 琦玉的小破站
subtitle: Alone
description: 我的个人博客
keywords: 个人博客;赛博朋克风网站;好看的个人博客;学习天地
author: 琦玉
language: en
timezone: Asia/Shanghai

# URL
## 在这里设置你的网站url。例如，如果你使用GitHub Page，将url设置为 'https://username.github.io/project'
url: https://qing-m.github.io
## 文章的永久链接格式
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
## 资源文件夹，这个文件夹用来存放内容
source_dir: source
## 公共文件夹，这个文件夹用于存放生成的站点文件
public_dir: public
## 标签文件夹
tag_dir: tags
## 归档文件夹
archive_dir: archives
## 分类文件夹
category_dir: categories
## Include code 文件夹，source_dir 下的子目录
code_dir: downloads/code
i18n_dir: :lang
## 跳过过指定文件的渲染。匹配到的文件将会被不做改动地复制 到 public 目录中。您可使用 glob 表达式来匹配路径
skip_render:

# Writing
## 新文章的文件名称
new_post_name: :month:day-:title.md # File name of new posts
## 预设布局
## Hexo 有三种默认布局：post、page 和 draft。
default_layout: post
## 在中文和英文之间加入空格
auto_spacing: false
## 把标题转换为 title case
titlecase: false # Transform title into titlecase
## 在新标签中打开链接
external_link:
  enable: true # 在新标签中打开链接
  field: site # 对整个网站（site）生效或仅对文章（post）生效
  exclude: '' # 需要排除的域名。主域名和子域名如 www 需分别配置
## 把文件名称转换为 (1) 小写或 (2) 大写
filename_case: 0
## 显示草稿
render_drafts: false
## 启动 Asset 文件夹
post_asset_folder: true
## 把链接改为与根目录的相对位址
relative_link: false
## 显示未来的文章
future: true
## 代码块的设置, 请参考 Highlight.js 进行设置
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
## 代码块的设置, 请参考 PrismJS 进行设置
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

#主页设置
# path:您的博客索引页的根路径。(默认= ")
# per_page:每页显示的帖子。(0 =禁用分页)
# order_by:发布顺序。(默认按日期降序排列)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
## 默认分类
default_category: uncategorized
## 分类别名
category_map: null
## 标签别名
tag_map: null

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

## 日期/时间格式
## 日期格式
date_format: YYYY-MM-DD
## 时间格式
time_format: HH:mm:ss
## 选项支持 'mtime', 'date', 'empty'
## 当 Front Matter 中没有指定 updated 时 updated 的取值
updated_option: 'mtime'

# Pagination
## 每页显示的文章量 (0 = 关闭分页功能)
per_page: 10
## 分页目录
pagination_dir: page

# Include / Exclude file(s)
## 在 Hexo 配置文件中，通过设置 include/exclude 可以让 Hexo 进行处理或忽略某些目录和文件夹。你可以使用 glob 表达式 对目录和文件进行匹配。
include:
exclude:
ignore:

# Extensions
## 当前主题名称。值为false时禁用主题
theme: icarus

# Deployment
## 部署部分的设置
deploy:
  type: git
  repo: git@github.com:qing-m/qing-m.github.io.git # 同步的仓库
  branch: gh-pages # 同步的分组
